"""empty message

Revision ID: 634de4d8b842
Revises: 2909ea156f56
Create Date: 2022-05-23 21:53:49.665410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634de4d8b842'
down_revision = '2909ea156f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jq_article_category',
    sa.Column('cat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=20), nullable=False),
    sa.Column('keywords', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cat_sort', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('dir', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jq_article_category')
    # ### end Alembic commands ###
